### ISSUE TITLE
0.13.5: %pg1 quest macro incorrectly resolves to his/her

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2339] opened 2022-05-17 01:27 UTC
**Describe the issue**

Quest macro %pg1 currently resolves to "his/her," based on the player character's gender.

Quest macro %g1 properly resolves to "he/she," based on the last character referenced, which is the foundation for %pg1. Therefore:

**Expected behavior**

%pg1 should be he/she based on the player character gender, but it is his/her instead.

**Comment by Interkarma** [comment] 2022-05-17 03:10
Just checking on this one. @ajrb committed the following in May 2021.

**Comment by Interkarma** [comment] 2022-05-17 03:13
Just checking the following. @ajrb committed the following in May 2021.

https://github.com/Interkarma/daggerfall-unity/commit/2bab357ffaa362b53be34faa92ea4b2dc74fe1fd

This would indicate someone tested %pg1 is the same as %pg3 and should resolve to his/her. It's an easy enough change to make %pg1 he/she instead. But hopefully we can get some more history of this if Hazelnut can remember.

It's possible the handling in DFU is correct and the quest is instead using the wrong macro. Or vice/versa depending on the quests tested against.

**Comment by JayH2971** [comment] 2022-05-17 03:18
> It's possible the handling in DFU is correct and the quest is instead using the wrong macro.

I just tested a quest of my own with %pg1, and it resolves to him/her.

**Comment by Interkarma** [comment] 2022-05-17 03:23
That's not what I mean. :) Your quest uses that macro sure - but that doesn't mean that's what the macro is supposed to do.

There's only one quest using this macro in classic, so it's quite difficult to say whether the quest is using the wrong macro or DFU's handling of the macro is incorrect. What other source do we have that %pg1 should be he/she instead of his/her?

That's why I tagged @ajrb. Hazel was most involved in the macro system buildout and might have some memory of how this behaviour was determined in the first place.

**Comment by KABoissonneault** [comment] 2022-05-17 12:04
As a reference, as of writing

%g and %g1 are he/she
%g2 is him/her
%g2self is himself/herself
%g3 is his/her

%pg is he/she
%pg1 is his/her
%pg2 is him/her
%pg2 is himself/herself
%pg3 is his/her

As you can see, only %pg1 is inconsistent with %g1.
Before https://github.com/Interkarma/daggerfall-unity/commit/2bab357ffaa362b53be34faa92ea4b2dc74fe1fd, everything was consistent, except for the comments, so I told Hazel about the comment, and he insisted that you, JayH, was expecting %pg1 to resolve to his/her, not he/she like %g1. Hence the change.

So my take is if JayH expects it to be he/she like %g1, we should revert it back to he/she (and fix the comment). At least according to comments, %pg macros are new to DFU, and are probably only used in classic quests because of manual fixes we've made? I could be wrong on that one, but in general, I expect QP mods to be the biggest client of this macro

**Comment by Interkarma** [comment] 2022-05-17 22:09
Thanks for the detail @KABoissonneault, that helps a lot. I'll change code and comments to be consistent with the other macro set and fixes Jay's issue here.

**Comment by df-ferital** [comment] 2022-05-18 05:23
Actually, %pg1 is not implementend in classic. This was probably an oversight since L0A01L00 is clearly expecting the player's pronoun there, not the killed NPC's one.

As a side note, %g2self does not exist in classic either. A macro always begins with `%` and ends with a space or a digit. So, in all quests using `%g2self`, classic uses `%g2`.

**Comment by petchema** [comment] 2022-05-18 07:32
> As a side note, `%g2self` does not exist in classic either. In QRC files, a macro is recognized when the quest parser reads a `%` and ends with a space or a digit. So, in all quests using `%g2self`, classic uses `%g2`.

That one will be troublesome for translation, let's say french translation of %g2 is lui/elle, %g2self will generate luiself/elleself, instead of expected transaction lui-même/elle-même.
So, I don't know if that was done on purpose, but handling %g2self as a separate macro will actually be useful.

But maybe that's what you meant; you didn't say it was a bug, just mention it was a discrepancy with classic.

**Comment by ajrb** [comment] 2022-05-18 19:29
Crikey mates. I blink and this appears... lol. 

So I am going to go through what has happened to the player gender macros over time:

The original list of macros to implement was taken from a list on UESP which now appears to be on this page in Appendix A: https://en.uesp.net/wiki/Daggerfall_Mod:Quest_hacking_guide#The_QRC_Files  I copied the macros and the comments, but left most unimplemented, and they've been implemented over time as usages were found. Comments were clarified/updated if solid info was discovered or figured out.

I added the player gender macros, which Ferital says are not in classic and were not in that UESP list, a few days later but have no recollection of what prompted me to do that. They were originally supposed to be a full set like g,g1,g2 etc but for the player name. Since these were new I decided that the duplicate that the g macros had with %g and %g1 being the same was pointless which is why I attempted to have a variation of %g3 his/hers (at that time) of his/her. I made a mistake when doing this and forgot to add the 1 on the end of pg1 method call by accident after copy pasting.

This mistake was later fixed but after @Interkarma had changed g3 and pg3 macros to his/her rather than his/hers (c81a9716) making them functionally equivalent to g1 and pg1... with the exception that pg1 was pointing at the wrong method still. When I had this pointed out (I believe someone pointed it out, quite possibly Jay but I don't recall) I realised I had neglected to add the 1 to pg1 method call and fixed it. (2bab357f) At this time I also added comments to the method PlayerPronoun1 to make clear that it did the same as PlayerPronoun3 since IKs change.

L0A01L00 didn't originally use %pg1 and it had 'his' hardcoded. The use of the DFU added macro is a DFU refinement made by @JayH2971 in July 2020 (8e03008f) when the macro was still erroneously pointed at the wrong method.


So what does this archaeology tell us? Mistakes were made. :-D

- I don't think my decision to try and make pgX macros more sensible and complete than the classic gX macros was a good one as most people in this discussion are assuming that pgX should work same as gX.
- When IK removed the hers from g3 macro, it could have stayed for the pg3 macro since it wasn't a 100% reflection of gX set.
- When I corrected pg1 to use the originally intended (by me) method it actually fixed the change Jay made to the vanilla quest L0A01L00 but I never checked quest pack or other mod quests.


@JayH2971 What has made you report this as an issue? Is it that you expect pgX set to reflect gX set of macros, and the inconsistency is catching people out?


So if anyone has got this far and is still awake.. I think we have 2 options; A) go with what I originally intended, or B) make pgX reflect gX exactly so it doesn't catch anyone out.

A)
%g and %g1 are he/she
%g2 is him/her
%g2self is himself/herself
%g3 is his/her

%pg is he/she
%pg1 is his/her
%pg2 is him/her
%pg2 is himself/herself
%pg3 is his/hers

B)
%g and %g1 are he/she
%g2 is him/her
%g2self is himself/herself
%g3 is his/her

%pg and pg1 is he/she
%pg2 is him/her
%pg2 is himself/herself
%pg3 is his/her

**Comment by ajrb** [comment] 2022-05-18 19:36
I would usually be quite insistent that my original plan was the clear answer, but not so sure on this one. The added utility and sense it brings is likely outweighed by confusion caused by people assuming it's the same as gX but for player - which is not an unreasonable assumption.

Anyway once people have offered their opinions and cast their votes for A or B I will submit a PR.

**Comment by Interkarma** [comment] 2022-05-18 22:37
Thank you for the extended breakdown Hazel. I really appreciate the archaeology. Amazing how the simple one are sometimes the most difficult to land on a fix for.

The way I ultimately parsed this one yesterday is the primary consumer of this macro is Jay, and his issue indicates the preference is for %pgX to match %gX. I also feel this also also makes things a bit clearer.

My vote is for option B and make the two sets reflect each other.

**Comment by JayH2971** [comment] 2022-05-18 23:47
> Is it that you expect pgX set to reflect gX set of macros, and the inconsistency is catching people out?

Yeah, I was looking for some mechanism to express %g1 for the player character, but no such macro exists. Of course any macro would work for me, but having pgX be an extension of gX would be the simplest approach IMO.

**Comment by ajrb** [comment] 2022-05-19 08:38
> > Is it that you expect pgX set to reflect gX set of macros, and the inconsistency is catching people out?
> 
> Yeah, I was looking for some mechanism to express %g1 for the player character, but no such macro exists. Of course any macro would work for me, but having pgX be an extension of gX would be the simplest approach IMO. I'm with B.

%pg is the same as %g1 (and %g) so I am confused why you say no such macro exists? All of them are he/she - what am I missing here?

I think I agree with you and Interkarma that %pgX should reflect %gX and that my idea to make the new macros make more sense was a poor one in hindsight. I'll draft up the PR tonight.

**Comment by JayH2971** [comment] 2022-05-19 08:40
That would be because I never use %g or %pg; this is my moment to learn of their existence :) I've always begun with %g1.

**Closed** 2022-06-01 00:13 UTC
