### ISSUE TITLE
Mods load order and settings are not saved on MacOs

### ISSUE THREAD

**Issue by TheLacus** [Interkarma/daggerfall-unity#1429] opened 2019-08-14 15:52 UTC
**Describe the bug**
It has been reported on forum that mods load order and settings are not saved to disk on MacOs. Specifically, load order file writing fails reporting the following message.

> Failed to write mod settings: Access to the path "/private/var/folders/5c/s4hd_4sx7qn5lj86w2h1bzpr0000gn/T/AppTranslocation/2290D9C4-8387-4323-943F-58ADD6CBC562/d/DaggerfallUnity.app/Contents/Resources/Data/StreamingAssets/Mods/Mod_Settings.json" is denied.`.

The correct path would be `/Applications/Games/Daggerfall Unity/DaggerfallUnity.app/Contents/Resources/Data/StreamingAssets/Mods/Mod_Settings.json`.

The following workaround has been reported:

> I've found that if I open the app bundle and navigate to "DaggerfallUnity.app/Contents/MacOS/DaggerfallUnity" and launch the Unix executable, which launches the game through the MacOS terminal app, everything works fine. Reverting to launching the game the standard way by double clicking the app bundle itself results in the original problem returning.

Probably `Application.streamingAssetsPath` is not writable on this platform, but i would like confirmation from other MacOs users. This is the first time the problem has been reported.

**Desktop:**
 - OS: MacOS 10.13.2.
 - Version: 0.10.4

**Additional context**
Issue reported at https://forums.dfworkshop.net/viewtopic.php?f=5&t=2251

**Comment by ShortBeard** [comment] 2019-08-17 08:50
I just tested this on:
**MacOS Version (High Sierra):** 10.13.3 
**DFUnity Version:** 0.10.4

And I can confirm that the load order settings are not being saved. They stay in the correct & intended order if you click "Save" and then immediately re-open the mod window again, but if you close DF Unity and re-open it, the load order resets.

**Comment by TheLacus** [comment] 2019-08-17 11:48
Thank you for confirmation.

I'll move mod configuration data to `persistentDataPath`, with two separate directories: `Mods/Build` and `Mods/Editor`, each one with this organization:

- `Mods.json`: load order
- `GUID`
    - `modsettings.json`: mod settings
    - `modpresets.json`: presets created in-game
    - `Presets/*.json`: custom presets to import
    - `Data`: writable directory accessible by mod

I'm open to feedback.

**Comment by TheLacus** [comment] 2019-08-17 12:50
@ShortBeard Would you be willing to test again on the branch `mods-data `? Thank you!

**Comment by ShortBeard** [comment] 2019-08-17 17:35
> @ShortBeard Would you be willing to test again on the branch `mods-data`? Thank you!

Seems to be fixed now! I tested the mod-data branch in both the Unity Editor and a built version and the mod load order seems to be saving correctly now - After exiting DFU and starting it again, the mods stay in the intended order that the user set.

**Comment by TheLacus** [comment] 2019-08-18 18:45
Thanks for the good news!

**Closed** 2019-08-18 19:09 UTC
Labels: bug, help wanted, mac
