### ISSUE TITLE
Quest A0C00Y12 - no quest item after second fight

### ISSUE THREAD

**Issue by info999** [Interkarma/daggerfall-unity#1386] opened 2019-08-03 16:03 UTC
If I cannot kill the thief at once and run for my life outside to get some heal - there is no book at the thief later. 
To get book I have to kill thief at first fight.
Too bad for roleplaying.

**Comment by JayH2971** [comment] 2019-08-03 18:21
For roleplaying, wouldn't it make sense that the thief would get rid of the book once he/she was caught? :eyes: 

I'll try loading this up and seeing, but I predict the issue is that the book doesn't transfer across multiple instances of the enemy.

https://github.com/Interkarma/daggerfall-unity/blob/master/Assets/StreamingAssets/Quests/A0C00Y12.txt

**Comment by JayH2971** [comment] 2019-08-03 19:03
I just tested it in classic and confirmed, it is as reported:

Classic: If you strike the enemy and then leave, the book will transfer to the new location.

DFU: If you strike the enemy and then leave, the book will not appear on the enemy at the new location.

**Comment by Interkarma** [comment] 2019-08-03 21:21
Fascinating! So the book is added to thief's inventory when struck the first time, and their inventory contents should persist across spawn positions when "place foe" is called to relocate thief to a second location?

**Comment by info999** [comment] 2019-08-04 01:13
> For roleplaying, wouldn't it make sense that the thief would get rid of the book once he/she was caught?
Well. Roleplaying permits to explain absolutely anything. It's not the problem.
The problem is how to finish the quest.

**Comment by JayH2971** [comment] 2019-08-05 14:48
> Fascinating! So the book is added to thief's inventory when struck the first time, and their inventory contents should persist across spawn positions when "place foe" is called to relocate thief to a second location?

Classic does that weird classic thing where it duplicates the first enemy's inventory onto the second, and then adds a new inventory (like when you do the Guard the Mages Guild quest and you notice the first enemy has 6 items, the next has 6+6 new ones, then the third one has 12+6 new ones, and so on). Here, the "second thief" you fight has the first one's inventory, including the quest book.

**Comment by Interkarma** [comment] 2019-08-05 21:45
Cheers, I had forgotten that. It seems the mechanism is quite basic in classic. I'll see if I can improve how this is handled in DFU.

**Comment by JorisVanEijden** [comment] 2019-08-20 14:40
It seems classic instantiates the resources (foes, items, npcs, locations) at the start of the quest and references the same instances.
Looks like DFU creates new instances every time a resource is "placed".
That would mean that in classic the thief would be hurt when showing up at the next location and in DFU it would be healthy again after every placement.

For this particular quest a workaround would be to place the book on the thief when it is killed, rather than injured.
Or, less elegantly, to place the book on the thief every time the thief is placed somewhere. But then it could be pickpocketed without a fight.

**Comment by JorisVanEijden** [comment] 2019-08-31 13:37
Possible instance of the same issue: https://forums.dfworkshop.net/viewtopic.php?f=29&t=2589

**Comment by Interkarma** [comment] 2019-08-31 17:50
An elegant solution for this one has already been implemented. Items added to Foes will now follow Foe to their next instance if the quest moves them.

Foes are a one to many resource with any number of instances created by quest. It's not generally viable to create these ahead of time or track them as singletons.

I'll close this one now as fix is already in code.

**Closed by Interkarma** 2019-08-31 17:50 UTC
Labels: questing
