### ISSUE TITLE
showing multiple lines over each other in a book `The First Scroll of Baan Dar`

### ISSUE THREAD

**Issue by alembiq** [Interkarma/daggerfall-unity#2243] opened 2021-09-15 06:47 UTC
![daggerfall_The_First_Scroll_of_Baan_Dar](https://user-images.githubusercontent.com/37374721/133383876-73b1a3f5-fc12-4997-b35f-c036dde29f9a.png)

### Daggerfall Unity 0.12.2

While reading some books ingame, I've found out that this book `The First Scroll of Baan Dar` is showing multiple lines over each other.
Just a minor inconvinience, but we all want this game to be perfect, right? :)

**Comment by Interkarma** [comment] 2021-09-15 07:47
Hey there. :) Daggerfall books have all kinds of errors inherited from classic data. DFU makes some attempts to auto-format things a bit better, but it's a half measure and can't correct everything. The full measure is to manually fix formatting across all in-game books until no formatting issues remain.

Books are scheduled to become part of localization data prior to 1.0, at which point our community can incrementally improve and reformat books in an open source way. I'll leave this issue open for now to raise awareness - although the problem is more general and applies to more books than just this one.

**Comment by petchema** [comment] 2021-09-15 18:58
There's already a mod we may draw from: Readable Books
https://forums.dfworkshop.net/viewtopic.php?f=14&t=1607

**Comment by alembiq** [comment] 2021-09-20 06:35
thank you for your help

**Comment by Interkarma** [comment] 2022-12-08 05:13
Books are now part of localized text system. This will be introduced starting from next release of DFU.
Localized book text files are found in StreamingAssets/Text/Books.
This specific issue will be fixed automatically due to how book text is handled. All other book text issues can be fixed by editing text file and submitting a PR to fix book in base game.

**Closed by Interkarma** 2022-12-08 05:13 UTC
