### ISSUE TITLE
(graphical error) Transparency and noise on some sprites in 0.13 preview

### ISSUE THREAD

**Issue by SocuciusTarkus** [Interkarma/daggerfall-unity#2246] opened 2021-09-21 01:22 UTC
Some sprites, from what I've seen occurring mainly outdoors, appear transparent in retro rendering with posterization or palettization enabled in the new 0.13.0 preview (Screenshots 1 and 2). In addition, when this post processing is enabled, some sprites and surfaces at times produce a grainy, visually noisy effect, though this is less of a problem than the transparency (Screenshot 3)

![test4](https://user-images.githubusercontent.com/78705929/134098090-df58724e-edee-49e2-a950-be9e2c23fa09.PNG)
![test2](https://user-images.githubusercontent.com/78705929/134098097-ef830dfc-fbb6-40fc-82fc-89994f7c5941.PNG)
![test3](https://user-images.githubusercontent.com/78705929/134098104-05ce8d66-0335-454a-8441-63714ec19134.PNG)

To reproduce this, just enable retro rendering on either resolution and set the post processing to posterization or palettization. The images were taken in the city of sentinel, though the bug I believe appears in other climates as well. The effect is most visible in foggy weather, though is still visible in all weather

Clearly, as seen in previous versions of the game, this visual noise and transparency are not supposed to occur

In addition, I know this probably isn't formal or right, but another bug that I'm adding as a side note that in this preview, shader maps are bugged, normal maps for instance don't appear as intended as seen in the following screenshot, but I'm not making it it's own issue since I assume that it's already well known since it is pretty glaring in mods which include shader maps

![normalenabled](https://user-images.githubusercontent.com/78705929/134098170-91906d15-c54a-4c3d-88ab-931b8e5123d3.PNG)

**Comment by Interkarma** [comment] 2021-09-21 03:29
The transparency isn't something new. It's a limitation of how classic sky needs to be selectively post-processed against depth map. Maybe something possible to refine later, but definitely not new to 0.13. You can see @petchema and I discussing it when this was implemented in this PR. The trick is most visible in foggy weather. You're also the first person I know of to notice and raise this. :) But it's not new and not considered a bug, more of a potential refinement.

https://github.com/Interkarma/daggerfall-unity/pull/1828#issuecomment-631984723

Regarding mods, DFU will use whatever shader and properties the mod assigns from its .dfmod. Mods should probably continue to use the Standard shader for PBR materials. All graphical mods will need to be updated to work with Linear colour space from 0.13. Any mods compiled for 0.12 won't look right from 0.13 until author issues an update created specifically for 0.13. This isn't considered a bug in DFU.

**Comment by Interkarma** [comment] 2021-09-21 04:53
Just to confirm something re. normal map issue. Is the mod compiled to a .dfmod or just using loose texture files? If it's just loose texture files then that could be an issue with new default shaders and I'll look into it. If you can link me to the mod, I'm happy to take a closer look. Cheers! :)

**Comment by petchema** [comment] 2021-09-21 05:44
I've seen dithering before, and in my case because it's a feature of my video driver (probably because my display device is not really capable of rendering 16M colors)
![Dithering settings](https://user-images.githubusercontent.com/1211431/134117552-d7dab2f7-d7f4-4ca0-8626-e62e2f4f137f.jpg)
)
Does it happen in 0.12?

**Comment by petchema** [comment] 2021-09-21 05:58
Mmmh, dithering look coarser in 320x200 than in 640x400, so I think it comes from the game stack, not drivers. 
Still need to check in previous versions

**Comment by Interkarma** [comment] 2021-09-21 06:27
Thanks Pango! Maybe the excess dithering static is a result of the new postprocess stack? I don't recall seeing this early in development of 0.13, and updating postprocess stack was one of the last things I did. I didn't spend a lot of time in retro mode after you fixed the initial colour space issue, so maybe I just missed it. I'll need to backtrack through changes to see where problem was introduced, but my suspicion right now is postprocess change.

**Comment by petchema** [comment] 2021-09-21 06:37
Yup, git bisect points at 
338cd6b2952d83d345ed261315548ae8d7590d6d is the first bad commit
commit 338cd6b2952d83d345ed261315548ae8d7590d6d
Author: Interkarma <interkarma@dfworkshop.net>
Date:   Tue Aug 24 13:50:47 2021 +1000

    Restore basic fog function
    
    Add PostProcessLayer to main camera.
    Create new object DefaultPostProcessVolume with empty profile.
    Restore WeatherManager code to toggle skybox based on weather.
    More work required before postprocessing changes completed.

**Comment by Interkarma** [comment] 2021-09-21 06:41
Good result, thank you. Now to work out the "why" part. :)

**Comment by SocuciusTarkus** [comment] 2021-09-21 22:35
> Just to confirm something re. normal map issue. Is the mod compiled to a .dfmod or just using loose texture files? If it's just loose texture files then that could be an issue with new default shaders and I'll look into it. If you can link me to the mod, I'm happy to take a closer look. Cheers! :)

I'm using loose texture files with improved interior lighting. The effect is slightly less with improved interior lighting disabled, though still present somewhat

**Comment by Interkarma** [comment] 2021-09-21 22:51
> Yup, git bisect points at
> [338cd6b](https://github.com/Interkarma/daggerfall-unity/commit/338cd6b2952d83d345ed261315548ae8d7590d6d) is the first bad commit
> commit [338cd6b](https://github.com/Interkarma/daggerfall-unity/commit/338cd6b2952d83d345ed261315548ae8d7590d6d)

It seems there's a hardcoded dither present since v2 of postprocessing stack.

https://forum.unity.com/threads/post-processing-causes-noise-when-no-effect-is-turned-on.796140/#post-5294748

I'll work out how to resolve.

**Comment by Interkarma** [comment] 2021-09-21 22:53
> I'm using loose texture files with improved interior lighting. 

Can you link me to the loose texture mod please?

**Comment by SocuciusTarkus** [comment] 2021-09-21 23:09
> > I'm using loose texture files with improved interior lighting.
> 
> Can you link me to the loose texture mod please?

https://www.nexusmods.com/daggerfallunity/mods/231

**Comment by Interkarma** [comment] 2021-09-22 02:40
I've embedded PPS v3.1.1 and manually edited out the "magic dither" from hidden shaders. This corrects static/noise introduced by 0.13.0 most observed when posterization/palettization enabled.

https://github.com/Interkarma/daggerfall-unity/commit/88ace56de6416f89233507967a5d2c8cb67603f2

I also find the billboard depth transparency limitation in fog is once again not very noticeable now that Unity isn't trying to dither our pixels. I'm happy with how this looks again now, and don't feel it needs to be addressed any further at this time.

Other than question about normal maps with new default shaders, that closes out the two problems in this issue. I'll take a look at normal maps from loose textures mod when I can and wrap up this issue.

**Comment by Interkarma** [comment] 2021-09-26 22:58
Have looked into question about normal maps now. I can confirm game is still loading normal maps normally, checking both in builds and inspecting generated material in editor shows normal maps as being present.

![image](https://user-images.githubusercontent.com/10426244/134826732-0cf0804b-c420-4275-88cf-5b41b04c881f.png)

I think a major reason these materials look different is new default shaders support Albedo+Normal+Emission channels only. Whereas the loose texture mod "Vanilla Normal Mapped DFU" also contains Height+Metallic channels, which are not supported by new default shaders at this time. There are three solutions:

1. Rework "Vanilla Normal Mapped DFU" into a .dfmod, where it's possible to use any preferred shaders. This would enable using the Standard shader again for loose textures as in 0.12 and below.
2. Add Height+Metallic support to the new default shaders.
3. Have loose texture loader fallback to Standard shader.

My preference is option 2. This is the most universal solution and simplest for modders. I'd also like to avoid the Standard shader unless the modder specifically uses it in their .dfmod. I'm looking into adding support for Height+Metallic to the new default shaders now.

**Comment by Interkarma** [comment] 2021-09-27 01:51
After evaluating this, I've decided that I will only restore Parallax map (height map) support to new default shader. Adding metallic support regresses to the PBR-related problems that I wanted to avoid with this change in the first place. That is to say the odd specular shine on everything and not using Lambertian reflectance. For some comparison screenshots:

**0.12.3** (using Standard shader)
![image](https://user-images.githubusercontent.com/10426244/134833161-0d1bcac2-083c-425a-991c-1e1634330b3d.png)

**0.13.0** (new DaggerfallDefault shader, albedo+normal+emissive support)
![image](https://user-images.githubusercontent.com/10426244/134833202-b54543bc-ad27-4a55-8a7a-5ffd70d713ae.png)

**0.13.1** (new DaggerfallDefault shader, albebo+normal+parallax+emissive support)
![image](https://user-images.githubusercontent.com/10426244/134833360-f124da00-8282-4271-89c3-a235dd8e6d50.png)

From editor showing textures loaded into material properties
![image](https://user-images.githubusercontent.com/10426244/134833278-2fdedf46-2cb1-4524-bf4f-ba5c8f90b4ac.png)

It's hard to see the difference between 0.13.0 and 0.13.1 in a static screenshot. The parallax effect is more noticeable when changing view direction or fiddling with the parallax strength slider in material properties.

Note this limitation is only for the default shader and loose texture import. A .dfmod can build replacement materials using whatever they like, e.g. Standard shader or something custom.

I'll close this one out now as everything has been looked at. The DaggerfallDefault shader will support _PARALLAXMAP keyword and maps in loose files from 0.13.1.

**Closed by Interkarma** 2021-09-27 01:51 UTC

**Comment by Interkarma** [comment] 2021-09-27 02:49
Playing with this one some more, I've noticed the file format of loose textures in "Vanilla Normal Mapped DFU" for metallic maps is incorrect. It uses the suffix  "_Metallic" instead of "_MetallicGloss" for metallic maps, so these are never loaded for this mod even under 0.12 and below.

![image](https://user-images.githubusercontent.com/10426244/134837885-fbd0249c-0cd2-4b1f-9518-25a3bcc18591.png)

To use this map from loose files requires setting filename as below.

![image](https://user-images.githubusercontent.com/10426244/134837997-584a1c90-479c-4378-b31c-c7f398b77582.png)

With that in mind, difference in appearance is now more down to using Lambertian reflectance rather than absence of metallic gloss map. Other lighting changes to environment (mod, settings.ini, etc.) will also contribute.

**Comment by SocuciusTarkus** [comment] 2021-09-27 20:27
> I'll close this one out now as everything has been looked at. The DaggerfallDefault shader will support _PARALLAXMAP keyword and maps in loose files from 0.13.1.
Thanks for all the help, once 0.13.1 is released, I'll mess with the naming of everything, see how it all looks, and upload a new file to the nexus. I actually did realize the _metallicgloss issue somewhat recently but haven't yet uploaded the file to the nexus. And I'll think about compiling a dfmod if I can figure out how to make it to where I can import the textures and they'll each automatically combine into materials. Being so unfamiliar with unity and c#, however, I'm only worried about messing up the new shaders, which I really enjoy. Worth a shot, either way!
