### ISSUE TITLE
Wrong questor data issues

### ISSUE THREAD

**Issue by JorisVanEijden** [Interkarma/daggerfall-unity#1688] opened 2020-02-02 14:54 UTC
When a quest adds a questor through the `add ... as questor` syntax, the wrong data is used.

In `Quest.AddQuestor()`
`person.IsQuestor = true;` calls `SetQuestorStatus(true)` which sets the questorData of the person to the data of the last clicked NPC. Which may very well not be the same person.
It then goes on the create a new questorData which is added to the quest, but not the Person.

This causes all kinds of subtle bugs with mixing up NPCs wherever the questorData of that Person is used.

Pull request that caused it: https://github.com/Interkarma/daggerfall-unity/pull/1583

Probably related reports:
Forum post: https://forums.dfworkshop.net/viewtopic.php?f=5&t=3368
Reddit post: https://www.reddit.com/r/daggerfallunity/comments/et6z8v/main_quest_glitched_please_help/

**Comment by df-ferital** [comment] 2020-02-02 20:02
Good catch! I will take a look at this to provide a better fix than my original PR.

**Comment by df-ferital** [comment] 2020-02-03 21:51
After further investigation, the issue looks quite hard to fix without breaking the original issue I wanted to fix (post success and failure greetings).

The problem is that DFU quest system relies on `StaticNPC.NPCData` to check if a clicked NPC was the questor of a particular quest. This works for all generic quest NPCs, but not for main quest ones, who are all added as questors using the `add _NPC_ as questor` command. In my previous PR, I incorrectly presumed that this command was always used after the questor NPC was clicked, but as you noticed, this is not always the case.

Now the problem is that there is absolutely no way to generate `StaticNPC.NPCData` on the fly for a given individual NPC, since this is related to a NPC location. I could use the NPC faction data, but since the Person `isQuestor` flag is set to false at the end of the quest by the  `drop _NPC_ as questor`, I can't know for sure that the individual the player is talking too was the questor.

One of the solution would be to keep a reference, in each quest instance, on the questor (since there is always one questor, as far as I know).

**Comment by df-ferital** [comment] 2020-02-03 22:47
I opted for the least intrusive solution which is to keep the `Person.isQuestor` flag to true even after the `drop _NPC_ as questor` command has been fired. This fixes the current issue while keeping PR #1583 intended fix and shouldn't break anything else.

**Comment by df-ferital** [comment] 2020-02-10 06:23
Fixed by PR #1693

**Closed** 2020-02-13 07:00 UTC
