### ISSUE TITLE
Mesh Replacement mod can cause the player to get stuck in the map marker

### ISSUE THREAD

**Issue by UncannyValley21** [Interkarma/daggerfall-unity#1706] opened 2020-02-12 17:11 UTC
Loading a saved game from an interior location in which the player doesn't have the Handpainted models enabled, with Handpainted models enabled, will cause an error and the player to collide with the Automap Player Beacons. (Player Marker Arrow and BeaconPlayerPosition)

**To Reproduce**
1. Go to an interior location such as a tavern
2. Save the game with the Handpainted models disabled
3. Load the game with the Handpainted models enabled 
4. The game will log an error (see below) and the player will be stuck in the player map beacon. 

[UnityError.txt](https://github.com/Interkarma/daggerfall-unity/files/4193736/UnityError.txt)

**Comment by XJDHDR** [comment] 2020-05-04 18:00
As I reported in this thread, adding a JSON that modifies an interior the player is in while Handpainted Models is already installed also triggers this bug:
https://forums.dfworkshop.net/viewtopic.php?f=5&t=3676

**Comment by Interkarma** [comment] 2021-07-20 23:07
@rossipaolo I haven't kept track of this one, can you recall if it has been resolved or should remain open? Cheers!

**Comment by rossipaolo** [comment] 2021-07-22 21:42
I think a few changes to the automap have been made since this issue was opened, i don't know if any of it affected this specific problem. I remember it was reported on forums ([link for more context](https://forums.dfworkshop.net/viewtopic.php?p=42383#p42383)) and also appeared with a broken loading screen, but that was only a result of an exception being thrown by automap when handpainted models mod is installed.

**Comment by Interkarma** [comment] 2021-07-22 22:07
Thank you for update. :) I'll investigate later then and see what comes of it.

**Comment by JorisVanEijden** [comment] 2021-09-05 07:48
I cannot reproduce this.

Versions used:
DFU 0.12.2
Handpainted Models 2.10
Loading Screen 2.6.1

Testcase 1:
- place ALCHAM01.RMB-1209-building14.json from XJDHDR in WorldData
- start game
- enable listed mods
- load save from XJDHDR (character 'Ree-Jah' save 'Bugged merchant - int')
- walk around shop
- leave shop

Testcase 2:
- start game
- disable listed mods
- load some save in a city
- enter a shop
- save game
- exit & restart  game
- enable both mods
- load save
- walk around shop
- leave shop

No errors or warnings in the logs during both tests.

**Comment by Interkarma** [comment] 2021-09-05 20:43
Thanks for feedback and testing @JorisVanEijden! I really appreciate the time taken to help on this one.

Issue sounds like it has been worked out via prior code changes or engine changes. The upgrade to 2019.4 solved a lot of sticking problems, odds are this was resolved at the same time.

I'll close this one now. We can open again if a test case to reproduce is found.

**Closed by Interkarma** 2021-09-05 20:43 UTC
Labels: bug
