### ISSUE TITLE
Wayrest Painting item not where it should be

### ISSUE THREAD

**Issue by Kerbannog** [Interkarma/daggerfall-unity#1444] opened 2019-08-20 00:46 UTC
I'm trying to finish the quest where you need to infiltrate castle wayrest to find a painting. But as described in the title, I'm exactly where the painting should be but there is nothing to pick up.
I tried to load my save without any mod activated but it doesn't change anything.
[SAVE0.zip](https://github.com/Interkarma/daggerfall-unity/files/3518178/SAVE0.zip)

**Comment by Interkarma** [comment] 2019-08-20 01:42
Issue here is that item was not assigned to target dungeon when quest launched. I just tried a clean start of quest and everything worked normally, possibly a bad interaction with one of your mods. Could you please let me know your mod loadout and order at the time quest began? I'll try to reproduce the original issue.

I have attached a fixed version of your save where I just manually set the item assignment. This should allow you to complete normally from this point. But if you can please get back to me about mods, I might be able to prevent this happening for others in future.

[SAVE706.zip](https://github.com/Interkarma/daggerfall-unity/files/3518267/SAVE706.zip)

**Comment by Kerbannog** [comment] 2019-08-20 01:56
Thank you very much  for the fast reply.
Here is I think what my load order looked like at the moment I took the quest.
But now that I think about it I would take a look at [Handpainted model replacement project (Release v1.83c)] since there is 4 of those new models around the spawning area of the painting.

[Archaeologists]
[Birds in Daggerfall 2.0]
[Cleaned SoundClips] (manually put)
[Convenient Clock]
[Daggerfall Autosave]
[Daggerfall Remastered Music Project (Released)] (manually put)
[Enhanced Sky]
[Dream HUD & Menu]
[Loading Screen]
[Mountains and Hills]
[Persistent Dungeons]
[Post Processing Effects]
[Dream SPRITES]
[Improved Interior Lighting]
[Real Grass 2]
[Dream Textures]
[Realtime Reflections]
[Villager Immersion Overhaul]
[NPC Flats Addendum] (manually put) 
[autoSave]
[(Slightly) Higher Res Vanilla Sprites v1.1] (manually put)
[Vibrant Wind]
[Handpainted model replacement project (Release v1.83c)]

The manually put ones are those that are not .dfmod files

**Comment by Interkarma** [comment] 2019-08-20 01:59
Cheers. I'll see if I can reproduce the original conditions leading to item not being placed correctly when quest began.

**Comment by Interkarma** [comment] 2019-08-20 05:27
I've not been able to reproduce issue again, even with your mod loadout. Problems like this can be difficult to pinpoint sometimes. :(

I've now added a new feature so that next builds will store up to 100 quest crashes permanently in save data. Hopefully next time this bug happens, the save data provided will help shed a bit more light on the cause.

I'll close this one now as core issue is currently unknown and missing item linkage is specific to your save. Thanks again for all the information!

**Closed by Interkarma** 2019-08-20 05:27 UTC

**Comment by Kerbannog** [comment] 2019-08-20 14:28
Ho, I forgot to tell something! I had to reset the main quest with a command because I took to much time to get in contact with the princess of wayrest. Maybe it has somethin to do in this issue.
