### ISSUE TITLE
Screenshot hotkey bug, two keys are being used

### ISSUE THREAD

**Issue by iamthegithubghost** [Interkarma/daggerfall-unity#2017] opened 2021-02-01 20:20 UTC
**Describe the bug**
I changed the screenshot hotkey ingame to "0" (Alpha0) and now even if I change or remove the hotkey binding "0" is still the screenshot hotkey no matter what.

**To Reproduce**
1. Go to the ingame main menu -> controls -> advanced
2. Change the screenshot binding to 0 (Alpha0)

**Expected behavior**
Even if I change or remove the screenshot binding "0" (Alpha0) is still being used as a screenshot hotkey somehow.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Daggerfall Unity beta 0.11.0

**Comment by Interkarma** [comment] 2021-02-02 00:18
Thanks for report. This one appears to be fixed by #1982, which will be included in upcoming builds. I'm not able to reproduce this in master branch of code.

I'll close for now, please don't hesitate to re-open if this still happens for you in 0.11.1.

**Closed by Interkarma** 2021-02-02 00:18 UTC
