### ISSUE TITLE
Advanced climbing bug - possible cause

### ISSUE THREAD

**Issue by red-moss2** [Interkarma/daggerfall-unity#2560] opened 2024-01-04 13:31 UTC
**Describe the issue**

As I understand it, climbing makes frequent checks involving Climbing skill and STR when in climbing mode, and will cause the player to fall if the check fails. So, if I have a character with say 11% Climbing and a STR of 43, my observed behaviour is trying to climb the face of a large house will see my character constantly slip down, reflecting my poor ability.

However, with Advanced Climbing System enabled, although initially it seems to honor the above system, after doing a bit of climbing your character is able to climb freely without any future fear of falling.

I think I have pinpointed the issue. If you start a new character with ACS enabled, your first attempt at climbing by going straight up a wall should behave as expected, your character will slip consistently. It seems however, that if you manage to complete an entire climb, the game stops making future slip checks thus making you a god-tier climber forever.

Looking at the code it is a feature that hanging doesn't do checks, which is fine. I think that it's completing a climb is what might be breaking future checks in ACS. Specific repro steps below.

**To Reproduce**

1. Enable ACS
2. Enable Start outside of Privateer's Hold option
3. Start a new game
4. Choose a character, I went High Rock, Male, Mage, Fast Start
5. Put all your points in anything but STR and Climbing so you end up with a character of about STR 50, Climbing 11% (i.e. quite weak)
6. Fast travel to Gothway Garden
7. Try and climb one of the bigger buildings by just going straight up, holding the move forwards key down but do not let go
8. You will observe that your character keeps slipping repeatedly, as expected from vanilla behaviour
9. Now, try a fresh climb somewhere and complete it
10. All future climbing will now be flawless

**Expected behavior**

With ACS turned on, we should still see weak climbers constantly slip and fall when they are doing anything except hanging, even after their first successful climb.

**Desktop (please complete the following information):**

 - OS: Windows
 - Version: 1.0.0

**Comment by KABoissonneault** [comment] 2024-01-04 19:35
I can confirm I can reproduce the issue. This code hasn't been touched for at least four years, and has lots of "TODOs" left. I'll try adding some debugging visualization and see where the issue is

**Comment by KABoissonneault** [comment] 2024-01-04 21:36
![image](https://github.com/Interkarma/daggerfall-unity/assets/5789925/ca2dabe5-71d5-45fd-9105-59ea0d4283c3)

Yeah as suspected, the code has an override for stopping the skill check once you're hanging at the top, but never turns it off.
The override stays on if you reload to a save before climbing (so it is not affected by save/load).
But goes back to false if you reboot the game.

Pretty sure all I need is to set this back to false if climbing stops

**Comment by KABoissonneault** [comment] 2024-01-25 01:42
Fixed in commit ba256805e5a229ffb0920dc072f0026b91ea250d

**Closed by KABoissonneault** 2024-01-25 01:42 UTC
