### ISSUE TITLE
Closing UI windows makes sound skip

### ISSUE THREAD

**Issue by petchema** [Interkarma/daggerfall-unity#1539] opened 2019-09-29 08:38 UTC
**Describe the bug**
Using Resources.UnloadUnusedAssets() in UserInterfaceWindow.CloseWindow() makes sound skip or stutter for many people, even with no mods (hence minimal memory usage).

Forums: https://forums.dfworkshop.net/viewtopic.php?f=27&t=10&p=25780#p25780

**To Reproduce**
Listen to sound while closing any UI window.

**Expected behavior**
Music and sounds to play seamlessly while using UI

**Desktop (please complete the following information):**
Tested with 0.10.7 on Linux, but it can be noticed on many gameplay videos

**Additional context**
Resoures.UnloadUnusedAssets() is supposed to be called automatically by Unity when new scene is loaded, I guess explicit call was added because Daggerfall Unity doesn't load many scenes (beside very early during execution). But could it be called in places that would be equivalent to scene loading: loading game, fast travel, teleport, entering/leaving buildings?
Alternatively, I personally used a patch that leaves the call in UserInterfaceWindow.CloseWIndow() but throttles garbage collection so it doesn't happen more than once every 5 minutes, which is sufficient to prevent eventual long term memory usage runaways.
Distant Terrain mod also seems to call Resoures.UnloadUnusedAssets()

**Comment by petchema** [comment] 2020-01-01 11:44
WIP:
https://github.com/Interkarma/daggerfall-unity/compare/master...petchema:load-scenes-gc

**Comment by Nystul-the-Magician** [comment] 2020-03-21 09:05
As far as I remember we put this in on purpose, we had a lot of ppl running out of memory and experiences crashes without because gc would not happen often enough

**Comment by petchema** [comment] 2020-03-21 14:11
I'm not advocating removing those calls altogether, because they're probably required (mainly because DFU doesn't use LoadScene() much I suppose).
However calling it from UserInterfaceWindow.CloseWindow() doesn't seem like a good idea, because it produces a noticeable skip for many people. Once you noticed that issue, it becomes unbearable.
I think we should investigate other options, like the patch I linked above. (investigating again could also be a good idea because we changed the version of Unity we use, so memory management may have improved).

Distant Terrain also contains a call to Resources.UnloadUnusedAssets() when origin is moved, as long as it does it's not concerned by how frequently we call UnloadUnusedAssets from DFU itself.

**Comment by Nystul-the-Magician** [comment] 2020-03-21 14:21
alright, makes sense ;)

**Comment by petchema** [comment] 2020-04-07 06:10
Something that may help is the incremental garbage collection that recent versions of Unity now feature (assuming it's GC that is actually what takes time in Resoures.UnloadUnusedAssets()).
However I think it was experimental in 2019.1 and is only in preview state in 2019.3; It also requires .NET 4.x compatibility

**Comment by Interkarma** [comment] 2020-04-11 22:37
I'm waiting for 2019.4 LTS to be the "final" version that carries us to 1.0 and into the foreseeable future. If that incremental GC feature is out of preview in that version, I'd be happy to enable and see how it rolls.

**Comment by jefetienne** [comment] 2020-04-12 17:49
I can't seem to reproduce the issue, but I attempted a fix with #1782.

**Comment by petchema** [comment] 2020-04-14 06:38
Just found this:
"Note that if you choose to use Resources.UnloadUnusedAssets, it is a very slow operation, and should only be called on a screen that won't show any hitches (such as a loading screen)."
https://docs.unity3d.com/Packages/com.unity.addressables@1.6/manual/MemoryManagement.html
But they don't provide any alternative way of unloading assets from AssetBundles...

**Comment by numidium** [comment] 2020-04-16 00:53
UnloadUnusedAssets is called by UserInterfaceWindow.CloseWindow so that would explain why there are complaints of stuttering on window close.

**Comment by Interkarma** [comment] 2020-04-16 01:05
>UnloadUnusedAssets is called by UserInterfaceWindow.CloseWindow so that would explain why there are complaints of stuttering on window close.

Yep, scroll up and check Pango's first post :) It's not everyone though. I've never experienced this personally, even on my old 2012 clunker that most of DFU was built on prior to upgrading last year.

We do need to unload asset bundles and clean up intermittently though, as DFU never changes scenes (which is when most Unity games do this). DFU generates a TON of procedural assets that will sit around in memory unless purged every so often. The trick is finding a good spot to do so. On closing UI seemed reasonable at the time, but I'm not married to it. Happy to move this to indoor/outdoor transitions or after fast travel if that helps reduce the problem and still provide periodic cleanup.

**Comment by HankTheDrunk** [comment] 2020-04-17 20:06
I did not experience this bug until 0.10.22 and it's made the game borderline unplayable with audio on. Closing any window causes the skip/stutter and it's maddening. I loot, sound stutter, I talk to an npc, sound stutter.
I know this post isn't helpful but I wanted to reply as a +1 I'm also having this problem. And for those that are it's damn near a deal breaker.

**Comment by jefetienne** [comment] 2020-04-17 21:06
@HankTheDrunk thanks for letting us know.

Can you tell us your specs? Is it a full stutter that freezes the game or is it just the audio? Does it occur immediately when you start playing, or is it more like 15 minutes into gameplay? If it is immediate, does it also happen when going from the setup wizard to the video?

**Comment by TheLacus** [comment] 2020-04-17 21:11
> Alternatively, I personally used a patch that leaves the call in UserInterfaceWindow.CloseWIndow() but throttles garbage collection so it doesn't happen more than once every 5 minutes, which is sufficient to prevent eventual long term memory usage runaways.

I think the original proposal by @petchema is a good idea for a simple and effective fix. Even if it might be only a partial solution, it should still be helpful given the number of reports that have been made recently and doesn't stop us from further discussion and improvements in the future.

**Comment by HankTheDrunk** [comment] 2020-04-18 05:11
People who use a lot of mods are far more likely to experience this problem....

To test I spam clicked Escape on my keyboard. This activates the clearing call over and over.
With many Mods the sound stutters for an extended period of time and is very noticeable
Without many Mods the sound doesn't stutter or only does so for less than 50ms

They reason I decided to try this simple test. I figured interkarma ran with minimal mods or none at all and hense he never has this stutter problem. So all the people annoyed about sound stutter are very likely running a lot of mods. However I am unsure if their system specs determine how many mods they can pile on before the stutter starts to happen noticeably.

@jefetienne I can't share my system spec's this account isn't secure, very sorry.

**Comment by petchema** [comment] 2020-04-18 11:48
> I think the original proposal by @petchema is a good idea for a simple and effective fix. Even if it might be only a partial solution, it should still be helpful given the number of reports that have been made recently and doesn't stop us from further discussion and improvements in the future.

Sounds good enough for me, I submitted it as a PR

**Comment by petchema** [comment] 2020-04-18 12:08
Another workaround that just occurred to me, if the only thing that can block in Resources.UnloadUnusedAssets() is indeed the call to System.GC.Collect(), then starting with Unity 2018.3 we could temporarily set GarbageCollector.GCMode to GarbageCollector.Mode.Disabled around the execution of UnloadUnusedAssets() so that GC.Collect() does nothing and UnloadUnusedAssets() is really as asynchronous as it claims to be.

**Comment by Interkarma** [comment] 2020-04-19 02:47
I've wanted to move to 2019.4 LTS for a while now, it's just not available yet. What about moving to latest 2019.3 for now then it's only a short step to 2019.4 LTS once available?

I just want to minimise the number of engine shifts as it breaks mods. But that shift is coming and I see it as a vital step towards 1.0.

**Comment by petchema** [comment] 2020-04-19 09:01
If binary compatibility is guaranteed between identical major versions, then that could be a plan.
Hopefully most mods will be upgraded, there's plenty of good stuff now but not all authors are still around and have enough time to maintain their mod(s) :(
I wonder if creating some kind of "preview" branch based on Unity 2019.x would help upgrading mods ahead or time, or if this will just increase the pain for everybody. I have no idea what are the best practices for such cases...

**Comment by Interkarma** [comment] 2020-04-19 15:21
I'm only hoping the final jump from 2019.3 to 2019.4 LTS won't break mods again. I honestly can't guarantee that. My preference would be to wait for the LTS version, but I'm willing to try an incremental approach. The shift to linear lighting is another step that will break some mods. So fun times ahead leading into beta, I think.

We can create a 2019 preview branch. It could get a bit sticky though as the number of changes required is going to result in a lot of conflicts with new PRs. It's a safe way to explore problem space however, even if never merged directly back to master.

**Comment by Interkarma** [comment] 2020-04-19 23:51
I've created a test branch for 2019.3.10f1 now. I don't plan to merge this one directly back to master, only to explore upgrade process further and release test builds to help modders prepare.

**Comment by petchema** [comment] 2020-05-07 21:02
This problem was mentionned in the forums again (about 0.10.22 for the record)
https://forums.dfworkshop.net/viewtopic.php?f=5&t=3687

**Closed** 2020-07-11 05:33 UTC
