### ISSUE TITLE
Linux 0.14.5: paintings do not display in inventory

### ISSUE THREAD

**Issue by JayH2971** [Interkarma/daggerfall-unity#2491] opened 2023-02-04 15:32 UTC
ISSUE:

A Windows user told me this does not happen for them, so this may be Linux-related. No mods, 0.14.5.

Clicking on any painting provides no full-size image of it in the inventory. The paintings were spawned by Biography questions in chargen and by the console.

![image](https://user-images.githubusercontent.com/37541932/216775756-a0e7f62b-2147-4f3b-adf1-8bf246719944.png)

The player log generated the following error after clicking:

> UnityException: Texture '' is not configured correctly to allow GetPixels
>   at (wrapper managed-to-native) UnityEngine.Texture2D.GetPixels32(UnityEngine.Texture2D,int)
>   at UnityEngine.Texture2D.GetPixels32 () [0x00001] in <0012ea2f37974907a308009fd693c396>:0 
>   at DaggerfallWorkshop.Utility.ImageReader.GetColors (DaggerfallWorkshop.ImageData imageData) [0x00015] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Utility.ImageReader.GetImageData (System.String filename, System.Int32 record, System.Int32 frame, System.Boolean hasAlpha, System.Boolean createTexture, System.Boolean createAllFrameTextures, System.Int32 alphaIndex) [0x0044d] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow.ShowInfoPopup (DaggerfallWorkshop.Game.Items.DaggerfallUnityItem item) [0x000d8] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow.LocalItemListScroller_OnItemClick (DaggerfallWorkshop.Game.Items.DaggerfallUnityItem item, DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow+ActionModes actionMode) [0x000c7] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow.LocalItemListScroller_OnItemLeftClick (DaggerfallWorkshop.Game.Items.DaggerfallUnityItem item) [0x00000] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.ItemListScroller.ItemButton_OnClick (DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent sender, UnityEngine.Vector2 position, System.Boolean rightClick, System.Boolean middleClick) [0x0007a] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.ItemListScroller.ItemButton_OnMouseClick (DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent sender, UnityEngine.Vector2 position) [0x00000] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at (wrapper delegate-invoke) <Module>.invoke_void_BaseScreenComponent_Vector2(DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent,UnityEngine.Vector2)
>   at DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent.MouseClick (UnityEngine.Vector2 clickPosition) [0x00008] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.BaseScreenComponent.Update () [0x00347] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Panel.Update () [0x00009] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Button.Update () [0x00000] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Panel.Update () [0x00049] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Panel.Update () [0x00049] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Panel.Update () [0x00049] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.Panel.Update () [0x00049] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterface.UserInterfaceWindow.Update () [0x00008] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallBaseWindow.Update () [0x00077] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallPopupWindow.Update () [0x00000] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.UserInterfaceWindows.DaggerfallInventoryWindow.Update () [0x00000] in <89ba9f00299043cca178a23f1cb68cb2>:0 
>   at DaggerfallWorkshop.Game.DaggerfallUI.Update () [0x000d8] in <89ba9f00299043cca178a23f1cb68cb2>:0

[BadPaintingsSave.zip](https://github.com/Interkarma/daggerfall-unity/files/10608962/BadPaintingsSave.zip). This save file looks different from the above image, but contains the same problem, with 9 paintings available.

EXPECTED BEHAVIOR:

An image of the painting should appear, like so:

![2023_02_04_10_20_52](https://user-images.githubusercontent.com/37541932/216775957-ed58ff85-5d8e-49fa-9b0d-5bfe81b0e0b3.jpg)

**Comment by petchema** [comment] 2023-02-05 10:17
Since that bug was almost silent I totally missed it...
But the cause is filename case mismatch, as I expected

**Comment by petchema** [comment] 2023-02-05 16:59
By the way, this class of issues can be diagnosed or temporarily fixed by running
`export MONO_IOMAP=case`
Before starting Daggerfall Unity
(source https://www.mono-project.com/docs/advanced/iomap/ )

**Comment by Interkarma** [comment] 2023-02-08 20:53
Resolved by #2492.

**Closed by Interkarma** 2023-02-08 20:53 UTC
