### ISSUE TITLE
Expose ability to change mod settings in game

### ISSUE THREAD

**Issue by rossipaolo** [Interkarma/daggerfall-unity#2004] opened 2021-01-27 18:00 UTC
The ability to change settings for supported mods in game is currently only available with the console command [change_modsettings](https://github.com/Interkarma/daggerfall-unity/blob/ca423ca3e19b3afd2110de419213bd6b61f72624/Assets/Game/Addons/UnityConsole/Console/Scripts/DefaultCommands.cs#L2675) and i wonder how many people know that this is possible at all. It should probably be made available from UI in the pause window, like control settings.

**Comment by Interkarma** [comment] 2021-04-30 03:37
Happy to put a button in somewhere. What about under Advanced control setting? It's a custom UI layout and has plenty of space for a new button without trying to cram it into the main controls UI.

**Comment by jefetienne** [comment] 2021-04-30 04:15
I [mentioned](https://github.com/Interkarma/daggerfall-unity/pull/1774#issuecomment-608610697) an idea to have a small drop-down menu in the corner of the pause menu in my "Added advanced controls window" PR but unfortunately I don't believe I ever got a response from it. What do you guys think?

I personally feel that if it is a setting window that isn't directly related to controls or input, that it would be better to keep it out of the navigation from Pause window -> "Controls" button.

**Comment by Interkarma** [comment] 2021-04-30 04:22
I'm sorry for not replying to that one @jefetienne. Yes, I'd be happy with that solution, and prefer it to placing under controls. :)

**Comment by rossipaolo** [comment] 2021-04-30 20:10
I also like it!

**Comment by jefetienne** [comment] 2021-05-01 06:31
Glad to hear! I might not be able to work on this the same speed I did last year, but I can try and get started on it.

**Comment by ajrb** [comment] 2021-05-09 10:17
Not sure how useful this will be for a lot of mod settings, as they're read once when the mod inits and configure it a certain way. We may need a flag or something indicating dynamic settings to make it visible which can be changed in game?

**Comment by Interkarma** [comment] 2021-05-09 11:29
>Not sure how useful this will be for a lot of mod settings, as they're read once when the mod inits and configure it to run a certain way. We may need a flag or something indicating dynamic settings to make it visible which can be changed in game?

That's an excellent point. Not all mods will support runtime changes, and giving modders the ability to limit this will be needed.

**Comment by ajrb** [comment] 2021-05-09 12:35
I think modders are in control, the issue is more messaging to players so they know which settings will make a difference in game. Generally this will be pretty obvious to those of us in the know, but we could get a lot of noise from confused players wondering why changing a setting in game does nothing.

**Comment by rossipaolo** [comment] 2021-05-09 15:12
What do you think of a flag for each group of settings?

**Comment by ajrb** [comment] 2021-05-09 15:22
I think it will need to be per setting. If set then the setting can dynamically affect a running game.

**Comment by jefetienne** [comment] 2021-07-04 19:22
According to the `ChangeModSettings` command, it only gets mod settings where:
```
mod.HasSettings && mod.LoadSettingsCallback != null
```
By default, there won't be an existing callback for a mod, so if it does have one, that proves the author's intentions to have runtime mod setting changes.

I think the best way to go about this would be either just to have a permanent label in the settings window saying "Some changes will not be applied until the game is restarted", or still have that label, but it will only appear on the condition of a setting being modified that has the editable flag set false. What do you guys think?

**Comment by Interkarma** [comment] 2021-07-04 22:02
The first option to always display restart disclaimer is easiest and I'm happy to start there. The second option is a nice to have and can be layered on top of the first. Mod authors who take the time to implement callback will probably appreciate the restart disclaimer disabling itself.

Then again, we have no idea if the callback will really apply all settings or not, so a basic disclaimer is also universal. It feels like first option is the best starting point and then it can be refined from there.

**Comment by Interkarma** [comment] 2021-07-19 00:01
I'll close this now that changes are merged. Thank you @jefetienne! :)

**Closed by Interkarma** 2021-07-19 00:01 UTC
Labels: UI, enhancement, mod system

**Comment by rossipaolo** [comment] 2021-07-24 22:00
Thank you for working on this feature @jefetienne!

**Comment by jefetienne** [comment] 2021-07-24 22:03
Anytime :)
