### ISSUE TITLE
Direction to same location fails.

### ISSUE THREAD

**Issue by JorisVanEijden** [Interkarma/daggerfall-unity#1449] opened 2019-08-20 13:49 UTC
**Bug description**
When a "Tell me about..." conversation reply mentions a direction to a location (through the `%di` token) it will fail when you are already at that location.

**To Reproduce**
1. Load the attached save [SAVE675.zip](https://github.com/Interkarma/daggerfall-unity/files/3520818/SAVE675.zip)
2. Open the console, use `talk_NpcsKnowEverything` and close the console.
3. Click on an npc.
4. Use "Tell me about.." to ask about "Evelyna Kingsmith".
5. Note the response: "Evelyna Kingsmith, eh?  A mysterious blue-cloaked woman who operates out of The Ashwing Residence, **...never mind...** of here. There may be more to it."
(You may have to ask about her a couple of times to get the location response)

**Expected behavior**
I expect the response to state "North of here" in stead of "...never mind... of here", since the Ashwing Residence building is to the North of the player's current position.

**Desktop:**
 - OS: Windows
 - Version: git master, commit 5ca7b52a1eb1c4d8e943df53c3fe1a196aecef79

**Additional context**
If you use "Where is..." to ask about Evelyna Kingsmith the reply will tell you she's to the north.

The "about" code at `Questing.Quest.QuestMacroDataSource.LocationDirection()` is only accurate to Location granularity.
The "where" code at `TalkManager.TalkManagerDataSource.LocationDirection` is accurate to building granularity but is coupled to `TalkManager.currentKeySubjectBuildingKey`.

We could copy the code from the talkmanager to the questdatasource, or rewrite the talkmanager code to split up the functionality to create a method that both can use.
But maybe it is possible to create something more generic (in the PlayerGps?) that can always give you the direction from the player to any Location, Building, Region, Npc, etc?

**Comment by Nystul-the-Magician** [comment] 2019-08-21 06:31
do you want to work on this or should I take a look?

**Comment by JorisVanEijden** [comment] 2019-08-21 08:16
I'm missing the experience and background with DFU to make an informed decision on the optimal way forward.
It's easy enough to make building granularity work in the QuestMacroDataSource. But having identical functionality in two very different parts of the code smells like a need for refactoring.
If you say to go for the localized minimal-change solution then I can work it out.
If you share the feeling this might be extracted and generalized to a different location then I'm a bit out of my depth as to where and how this should go.

**Comment by Nystul-the-Magician** [comment] 2019-08-21 11:42
hmm not sure, I wrote the TalkManager variant and tested it back then
not sure from when the QuestMacroDataSource implementation is and where the differences lie.
I agree that having a unified solution would be best
for now I will try to fix the reported bug
afterwards I will try to understand the differences between the two approaches and try to merge them

**Comment by Nystul-the-Magician** [comment] 2019-08-21 15:03
update: this is a bit more trickier than expected, but I am confident about fixing it
first: direction macro can either resolve local (buildings) or remote (locations) place resources. First case results in the bug (QuestMCP method not handling this case)
second: direction resolving relies on player advanced transforms (correct for outdoors but not for indoors) - so I get different directional hints for asking for buildings indoors and outdoors - this is another bug that needs to be solved. I need to store the last transform position of player advanced before transition to interiors happen so that this stored position can be used for correct direction computation when asking indoors

**Comment by Interkarma** [comment] 2019-08-22 00:13
Thank you Nystul! I love hearing when you're confident, it means a good fix is incoming. :)

**Comment by Nystul-the-Magician** [comment] 2019-08-22 14:18
one question since I stumbled across this "issue":
when in the same building as the target person, npcs still may not know about the person - should we change this so the npcs will always know when a person is in the same building.
It is a question of realism, but I laugh so much when asking the king about his wife and has absolutely no clue who she is :D :D :D - he might be denying or drunk though - but half of the court ppl refusing to know her is hilarious

**Comment by Nystul-the-Magician** [comment] 2019-08-23 08:12
I decided to go for option 1) like vanilla but make it so that npcs outside the region will not know anything about locations outside their region, they might know about persons in their region (by design this means they also might know that those persons live in a different location (town))

**Comment by Interkarma** [comment] 2019-08-23 08:24
I'm so sorry Nystul. I had intended to respond to your earlier post, but was distracted by other little issues today.

I'm happy with your choices here and looking forward to playing with your improvements.

**Comment by Nystul-the-Magician** [comment] 2019-08-23 09:33
ok this is how I did it:
- tell me about topics will be available everywhere
- only npcs in the same region as the place or person resource will give useful answers
- %di macro will resolve to just compass direction if npc is in same location as person resource
- %di macro will resolve to name of remote location, followed by compass direction to remote location if npc is in different location

**Closed** 2019-08-31 18:25 UTC
