### ISSUE TITLE
Replacing Dungeon Block breaks switches

### ISSUE THREAD

**Issue by XJDHDR** [Interkarma/daggerfall-unity#1826] opened 2020-05-17 07:33 UTC
**Describe the bug**
I've found that if you replace a Dungeon Block Record that contains switches, those switches stop working. I have attached a zip archive to this bug report you can use to test this issue. It contains a **N0000005.RDB.json** that has not been modified in any way. If you use the dumpblock command, you will get the same file that I attached.

It also contains a save game you may use to test this where my character is inside a copy of **N0000005.RDB**. The room he is standing in contains a switch that is used to open and close the trap door that is visible through the doorway. There are also three other rooms in the area that each contains a switch that damages the player's health when activated.

[Trapdoor bug report files.zip](https://github.com/Interkarma/daggerfall-unity/files/4639795/Trapdoor.bug.report.files.zip)

**To Reproduce**
1. Load the attached savegame without the replacement RDB installed. 
2. Activate the switch in the room you're standing in and the open trap door will close.
3. Go to any of the other three rooms and activate their switch. The player will take damage.
4. Exit the game and drop the **N0000005.RDB.json** file into _StreamingAssets\WorldData_.
5. Load the save and repeat steps 2 and 3.
6. The trap door's switch will no longer close the trap door and the other switches no longer damage the PC.

**Expected behavior**
The switches to either open the trap door or damage the player regardless of whether the replacement RDB is installed or not.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: 0.10.23

**Comment by Interkarma** [comment] 2020-05-17 09:09
Who would be best to assign this one - @TheLacus? @ajrb?

**Comment by BadLuckBurt** [comment] 2020-05-17 13:18
I investigated this a little by examining the RDB.json dump and loading the N0xxxx5.RDB block in the Unity editor. 

It looks like the RDB.json dump loses the NextObjectIndex reference to the trapdoor model, there are two switches this happens to.

The first one is the lever that opens the trapdoor (model ID 54001) at the bottom of the pit:
`
{
                        "Position": 10155,
                        "Index": 60,
                        "XPos": 752,
                        "YPos": -336,
                        "ZPos": 352,
                        "Type": "Model",
                        "Resources": {
                            "ModelResource": {
                                "XRotation": -256,
                                "YRotation": 0,
                                "ZRotation": 0,
                                "ModelIndex": 44,
                                "TriggerFlag_StartingLock": 2,
                                "SoundIndex": 42,
                                "ActionResource": {
                                    "Position": 10203,
                                    "Axis": 2,
                                    "Duration": 16,
                                    "Magnitude": 512,
                                    "NextObjectIndex": -1,
                                    "Flags": 8
                                }
                            }
                        }
                    }
`
The second one is supposed to move the statue with model ID 62330 that is sitting on top of a quest marker:
`
{
                        "Position": 29264,
                        "Index": 0,
                        "XPos": 1152,
                        "YPos": -1048,
                        "ZPos": 1350,
                        "Type": "Model",
                        "Resources": {
                            "ModelResource": {
                                "XRotation": 0,
                                "YRotation": 0,
                                "ZRotation": 0,
                                "ModelIndex": 44,
                                "TriggerFlag_StartingLock": 2,
                                "SoundIndex": 20,
                                "ActionResource": {
                                    "Position": 29312,
                                    "Axis": 5,
                                    "Duration": 16,
                                    "Magnitude": 256,
                                    "NextObjectIndex": -1,
                                    "Flags": 8
                                }
                            }
                        }
                    }
`

It looks like the links aren't preserved in these particular cases but they are present in the editor after the RDB block has loaded. The dump does contain the links between the levers that are supposed to hurt you and the lever box they sit in (which actually has the hurt-flag)

I had to comment out the treasure generation code and some other stuff to allow the block to fully generate in the editor, is it possible the **dumpblock** command runs into the same issue?

I doubt I'll be able to fix this on my own but I hope this helps shed some light on things.

**Comment by ajrb** [comment] 2020-05-19 16:36
Will need to do some investigation around this, great start Burt - thanks for that.

**Comment by BadLuckBurt** [comment] 2020-05-19 17:59
> 
> 
> Will need to do some investigation around this, great start Burt - thanks for that.

You're welcome, please let me know once you're ready to look into this. I've done some more investigating and did find a way to make them work again but we should probably discuss it directly.

**Comment by XJDHDR** [comment] 2020-07-03 17:52
Does anyone have any updates they are willing to share?

**Comment by BadLuckBurt** [comment] 2020-07-04 07:33
> 
> 
> Does anyone have any updates they are willing to share?

Not really but the main issue is this:

In the original data, the linked objects are determined by the Position value which is referenced by NextObjectOffset and PreviousObjectOffset.

The world data dumps do not save the NextObjectOffset and PreviousObjectOffset but instead try to use NextObjectIndex which is an array index of an RdbObject list. 

I did a test by making the NextObjectOffset and PreviousObjectOffset public properties so they would be exported and with those dumps, everything works as intended because the code that actually creates the links uses those properties and not the NextObjectIndex to link things together. 

I wrote a quick scripts to analyse the several RdbObject lists that are in an RDB dump and found that sometimes the objects reference an object that's in another list and that's where linking through index fails.

I think the way to go is to make the Offset properties public and let DFU link objects through those again but wanted to discuss this with @ajrb first as there may be a reason why it was set up this way that I'm not aware of.

**Comment by ajrb** [comment] 2020-07-21 16:12
Thanks again Burt, I've not had time to look into this. Sounds like that is the way to fix this, and they're only marked that way because the data is only used for initial processing and should not be accessed subsequent to that. Only question is whether that's important to preserve, I'll ask @Interkarma to offer an opinion on that. If so then I can add directives for the serializer which should work, but is easier just to convert them to public access which I did for a few other things.

**Comment by Interkarma** [comment] 2020-07-21 19:54
Happy for any required private fields to be made public for the sake of serialisation/deserialisation of these linkages.

**Comment by BadLuckBurt** [comment] 2020-07-22 05:53
@ajrb You're welcome. I've given it some more thought in the meantime. It's probably easiest to just make the properties public so the existing code can do it's thing without having to rewrite anything. It will also make it easier for modding since the Position acts like an ID. I won't mind snatching this one off your plate this weekend seeing how we got the OK from @Interkarma (thanks!)

**Comment by ajrb** [comment] 2020-07-23 20:10
@BadLuckBurt Very happy for you to do it, and I will review. I think it will be better because I wouldn't test it... whereas you will.

**Comment by BadLuckBurt** [comment] 2020-07-24 05:36
@ajrb no problem, will do it this Sunday using the new master branch

**Comment by ajrb** [comment] 2020-08-31 20:08
@BadLuckBurt has returned on Discord at least... anyway he said that he would look at this imminently.

**Comment by BadLuckBurt** [comment] 2020-08-31 21:30
> 
> 
> @BadLuckBurt has returned on Discord at least... anyway he said that he would look at this imminently.

Not just on Discord. I'm pushing the fix tomorrow, I need to go to bed. Had to reinstall the old Unity because I already moved to the 2019 version. In any case, only one final test and I'm ready to upload it.

**Comment by BadLuckBurt** [comment] 2020-09-01 20:59
Right, I have put in the pull request: https://github.com/Interkarma/daggerfall-unity/pull/1912

@XJDHDR If you merge my dungeon-activator-fix branch, redump N00000005.RDB and do your changes in the new file it should work again. Let me know if it doesn't and I'll dig into it some more but as far as I can tell, this was the only bit missing.

**Comment by XJDHDR** [comment] 2020-09-01 21:03
> If you merge my dungeon-activator-fix branch, redump N00000005.RDB and do your changes in the new file it should work again. Let me know if it doesn't and I'll dig into it some more but as far as I can tell, this was the only bit missing.

Thanks. I'll give it a try when I get back home tonight.

**Comment by XJDHDR** [comment] 2020-09-02 05:21
@BadLuckBurt 
I just finished testing your changes and they fixed the problem. In N0000005.RDB, the switches move the targeted objects again and the switches and trap doors hurt the player. I did notice that the public variables are required to both dump and use the correct Dungeon Blocks. In 0.10.24, the switches still don't work even with the fixed RDB dumps. So any mods that are affected by this will need to set 0.10.26 as their minimum.

**Comment by BadLuckBurt** [comment] 2020-09-02 05:31
Are you sure about the 0.10.24 not working? They worked for me and there is no reason it shouldnt, all that has changed is that the offsets are exported and loaded in. For that to work, you will need to have a 0.10.24 build where the offset properties are public otherwise the serializer will not load them when it loads the RDB.JSON

**Comment by XJDHDR** [comment] 2020-09-02 06:31
I was referring to the default 0.10.24 build. If I modify the source to make those variables public, it works in that version as well. I made that remark because I highly doubt that Interkarma is going to backport this fix into any older version.

**Comment by BadLuckBurt** [comment] 2020-09-02 06:35
Gotcha, just wanted to clear up any possible confusion 👍

**Closed** 2020-09-08 07:48 UTC
