### ISSUE TITLE
Quest Tracking - Unknown Quests in Dialogue

### ISSUE THREAD

**Issue by Burin077** [Interkarma/daggerfall-unity#1536] opened 2019-09-28 23:48 UTC
**Describe the bug**
When looking through the dialogue options after having played the game and completing a few small quests (For example, the "A Delivery" quest from the House of Dibella) a series of unknown people and objects appears in the "Tell Me About..." dialogue section, as well as unknown Residential locations not relating to any previous quests.

**To Reproduce**
1: Accept quests from any Quest Giver, and complete the quests as indicated. (Make sure to accept/complete multiple quests in a single day for the most immediate effect.)
2: After completing said quests, go talk to any NPC and attempt to look at the "Tell Me About..." or "General" locations.
3: You will see a number of unusual names/items/locations have appeared that do not have relevance to any previous quests you have completed.

**Expected behavior**
I should not be seeing random talking points showing up in my dialogue options; they should either relate to currently-running quests, or be something relating to the locale I am currently in.

**Screenshots**
![DagUnityBug5](https://user-images.githubusercontent.com/54295726/65823645-bfb9d000-e21f-11e9-99bc-2c3c636dde17.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Version/Build: 10.0.17763

**Additional context**
- The residential locations only seem to show up when a quest is currently active; the locations show up along with the actual location you would need during a quest. (For example, I might get the Moorsley Residence as the location I need to go to, however 3-4 other residences will also show up as talking point options.)
- Clicking on the extra talking points results in no reply from the NPC. Further, if you attempt to talk to the NPC about anything thereafter, they no longer respond. 
- I have found a workaround that rebooting the game clears out these invalid locations/talking points. As far as issues with no response from the NPC, you can start getting responses from them again if you ask them about a "Regional" option, such as "Any Temple of Kynareth."

**Comment by Nystul-the-Magician** [comment] 2019-09-29 12:16
I think this intended behaviour since the entries are there until the quests end

**Comment by Burin077** [comment] 2019-09-29 15:51
It's intended for irrelevant quest details to show up in the dialogue window? I didn't get the quests those entries even relate to; if it were related to the quests I took I could understand, but a quest I didn't even take?

**Comment by ajrb** [comment] 2019-09-29 20:21
Burin, can you say if you're using the new quest listbox option or not please?

**Comment by Burin077** [comment] 2019-09-29 21:20
> 
> 
> Burin, can you say if you're using the new quest listbox option or not please?


Are you talking about the "TalkWindow Modern Style" option? I am using that, yes; now that you mention it.

- B

**Comment by JayH2971** [comment] 2019-09-30 15:14
No, ajrb means the setting to show all available quests in a list format instead of being offered quests one by one.

**Comment by Burin077** [comment] 2019-09-30 17:29
> 
> 
> No, ajrb means the setting to show all available quests in a list format instead of being offered quests one by one.

You mean the newest feature that allows users to access what quests they want? "Guild Quest Player Selection?" That is on, yes.

- B

**Comment by ajrb** [comment] 2019-09-30 17:37
Right I think that may be a source of the issue. @JorisVanEijden has found some issues caused by parsing all the quests to prepare the list. Not sure if he's in the process of fixing the issues or not.

For the time being, you can prevent this issue by not using the quest list boxes until the bug is resolved.

**Comment by Burin077** [comment] 2019-09-30 17:44
> 
> 
> Right I think that may be a source of the issue. @JorisVanEijden has found some issues caused by parsing all the quests to prepare the list. Not sure if he's in the process of fixing the issues or not.
> 
> For the time being, you can prevent this issue by not using the quest list boxes until the bug is resolved.

Thanks much for the response and details; this helps narrow down the issue a whole lot in regards to what was causing some of the weird dialogue issues and non-responses.

- B

**Comment by JorisVanEijden** [comment] 2019-10-03 16:37
Yes, this will be fixed with https://github.com/Interkarma/daggerfall-unity/pull/1533

**Comment by ajrb** [comment] 2019-10-22 18:24
Need confirmation that this is fixed.

**Comment by petchema** [comment] 2019-11-05 13:14
It seems there's still some issues in dialogues;
Forums: https://forums.dfworkshop.net/viewtopic.php?f=25&t=2965&start=10#p34188

**Closed** 2019-12-15 21:37 UTC
